package com.lbg.project.models.catsMock

import com.lbg.project.models.Breed
import com.lbg.project.models.Weight


data class MockBreed(
    val adaptability: Int = 23,
    val affection_level: Int = 24,
    val alt_names: String = "cat",
    val bidability: Int = 0,
    val cat_friendly: Int = 10,
    val cfa_url: String = "https://google.com/",
    val child_friendly: Int = 0,
    val country_code: String = "91",
    val country_codes: String = "+91",
    val description: String = "cats breed info",
    val dog_friendly: Int = 1,
    val energy_level: Int = 30,
    val experimental: Int = 50,
    val grooming: Int = 1,
    val hairless: Int = 0,
    val health_issues: Int = 9,
    val hypoallergenic: Int = 0,
    val id: String = "ID",
    val indoor: Int = 0,
    val intelligence: Int = 0,
    val lap: Int = 123445,
    val life_span: String = "Small",
    val name: String = "Nice cat",
    val natural: Int = 0,
    val origin: String = "China",
    val rare: Int = 10,
    val reference_image_id: String = "imageID",
    val rex: Int = 0,
    val shedding_level: Int = 3,
    val short_legs: Int = 4,
    val social_needs: Int = 5,
    val stranger_friendly: Int = 6,
    val suppressed_tail: Int = 7,
    val temperament: String = "cool",
    val vcahospitals_url: String = "https://google.com/",
    val vetstreet_url: String = "https://google.com/",
    val vocalisation: Int = 0,
    val weight: Weight = toResponseCatBreedWeight(MockWeight()),
    val wikipedia_url: String = "https://google.com/"
)

fun toResponseCatBread(mockBreed: MockBreed): Breed {
    return Breed(
        mockBreed.adaptability,
        mockBreed.affection_level,
        mockBreed.alt_names,
        mockBreed.bidability,
        mockBreed.cat_friendly,
        mockBreed.cfa_url,
        mockBreed.child_friendly,
        mockBreed.country_code,
        mockBreed.country_codes,
        mockBreed.description,
        mockBreed.dog_friendly,
        mockBreed.energy_level,
        mockBreed.experimental,
        mockBreed.grooming,
        mockBreed.hairless,
        mockBreed.health_issues,
        mockBreed.hypoallergenic,
        mockBreed.id,
        mockBreed.indoor,
        mockBreed.intelligence,
        mockBreed.lap,
        mockBreed.life_span,
        mockBreed.name,
        mockBreed.natural,
        mockBreed.origin,
        mockBreed.rare,
        mockBreed.reference_image_id,
        mockBreed.rex,
        mockBreed.shedding_level,
        mockBreed.short_legs,
        mockBreed.social_needs,
        mockBreed.stranger_friendly,
        mockBreed.suppressed_tail,
        mockBreed.temperament,
        mockBreed.vcahospitals_url,
        mockBreed.vetstreet_url,
        mockBreed.vocalisation,
        mockBreed.weight,
        mockBreed.wikipedia_url
    )
}